package il.co.skystar.utils

import retrofit2.http.GET

object Constants {

    const val BASE_URL = "https://data.gov.il/api/3/"
    const val RESOURCE_ID = "e83f763b-b7d7-479e-b172-ae981ddc6de5"

    val flagDict = mapOf<String, String>(
        "ALBANIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/1280px-Flag_of_Albania.svg.png",
        "ARMENIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/1920px-Flag_of_Armenia.svg.png",
        "ARGENTINA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/1280px-Flag_of_Argentina.svg.png",
        "AUSTRIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/1280px-Flag_of_Austria.svg.png",
        "AUSTRALIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/1920px-Flag_of_Australia_%28converted%29.svg.png",
        "AZERBAIJAN" to "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1200px-Flag_of_Azerbaijan.svg.png",
        "BAHRAIN" to "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/1920px-Flag_of_Bahrain.svg.png",
        "BELARUS" to "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/1920px-Flag_of_Belarus.svg.png",
        "BELGIUM" to "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/1024px-Flag_of_Belgium.svg.png",
        "BRAZIL" to "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/1080px-Flag_of_Brazil.svg.png",
        "BULGARIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/1920px-Flag_of_Bulgaria.svg.png",
        "CANADA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/1920px-Flag_of_Canada_%28Pantone%29.svg.png",
        "NIGERIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/1920px-Flag_of_Nigeria.svg.png",
        "RWANDA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/1280px-Flag_of_Rwanda.svg.png",        "CHILE" to "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/1280px-Flag_of_Chile.svg.png",
        "CHINA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/1200px-Flag_of_the_People%27s_Republic_of_China.svg.png",
        "CROATIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/1920px-Flag_of_Croatia.svg.png",
        "CYPRUS" to "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/1280px-Flag_of_Cyprus.svg.png",
        "CZECH REPUBLIC" to "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/1200px-Flag_of_the_Czech_Republic.svg.png",
        "DENMARK" to "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/768px-Flag_of_Denmark.svg.png",
        "EGYPT" to "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/1280px-Flag_of_Egypt.svg.png",
        "ETHIOPIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/1920px-Flag_of_Ethiopia.svg.png",
        "FINLAND" to "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/1200px-Flag_of_Finland.svg.png",
        "FRANCE" to "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/1280px-Flag_of_France.svg.png",
        "GEORGIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/1200px-Flag_of_Georgia.svg.png",
        "GERMANY" to "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/1920px-Flag_of_Germany.svg.png",
        "GREECE" to "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/1280px-Flag_of_Greece.svg.png",
        "HUNGARY" to "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/1920px-Flag_of_Hungary.svg.png",
        "ICELAND" to "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/1280px-Flag_of_Iceland.svg.png",
        "INDIA" to "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/1280px-Flag_of_India.svg.png",
        "IRELAND" to "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/1200px-Flag_of_Ireland.svg.png",
        "ISRAEL" to "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/1200px-Flag_of_Israel.svg.png",
        "ITALY" to "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/1200px-Flag_of_Italy.svg.png",
        "JAPAN" to "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png",
        "JORDAN" to "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/1200px-Flag_of_Jordan.svg.png",
        "KAZAKHSTAN" to "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/1920px-Flag_of_Kazakhstan.svg.png",
        "LATVIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/1920px-Flag_of_Latvia.svg.png",
        "LITHUANIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/1200px-Flag_of_Lithuania.svg.png",
        "MALDIVES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/1280px-Flag_of_Maldives.svg.png",
        "MALTA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/1280px-Flag_of_Malta.svg.png",
        "MEXICO" to "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/1200px-Flag_of_Mexico.svg.png",
        "MOLDOVA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/1200px-Flag_of_Moldova.svg.png",
        "MONTENEGRO" to "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/1920px-Flag_of_Montenegro.svg.png",
        "MOROCCO" to "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/1280px-Flag_of_Morocco.svg.png",
        "NETHERLANDS" to "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1280px-Flag_of_the_Netherlands.svg.png",
        "NORWAY" to "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/1280px-Flag_of_Norway.svg.png",
        "PERU" to "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/1280px-Flag_of_Peru.svg.png",
        "PHILIPPINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/1200px-Flag_of_the_Philippines.svg.png",
        "POLAND" to "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/1280px-Flag_of_Poland.svg.png",
        "PORTUGAL" to "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1280px-Flag_of_Portugal.svg.png",
        "QATAR" to "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/1920px-Flag_of_Qatar.svg.png",
        "ROMANIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/1280px-Flag_of_Romania.svg.png",
        "RUSSIAN FEDERATION" to "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/1200px-Flag_of_Russia.svg.png",
        "SAUDI ARABIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/1200px-Flag_of_Saudi_Arabia.svg.png",
        "SERBIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/1280px-Flag_of_Serbia.svg.png",
        "SEYCHELLES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/1920px-Flag_of_Seychelles.svg.png",
        "SINGAPORE" to "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/1200px-Flag_of_Singapore.svg.png",
        "SLOVAKIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/1280px-Flag_of_Slovakia.svg.png",
        "SLOVENIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/1920px-Flag_of_Slovenia.svg.png",
        "SOUTH AFRICA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/1280px-Flag_of_South_Africa.svg.png",
        "SOUTH KOREA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/1200px-Flag_of_South_Korea.svg.png",
        "SPAIN" to "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Bandera_de_Espa%C3%B1a.svg/1280px-Bandera_de_Espa%C3%B1a.svg.png",
        "SRI LANKA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/1200px-Flag_of_Sri_Lanka.svg.png",
        "SWEDEN" to "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/1200px-Flag_of_Sweden.svg.png",
        "SWITZERLAND" to "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Switzerland_%28Pantone%29.svg/800px-Flag_of_Switzerland_%28Pantone%29.svg.png",
        "TANZANIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/1280px-Flag_of_Tanzania.svg.png",
        "THAILAND" to "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/1200px-Flag_of_Thailand.svg.png",
        "TURKEY" to "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/1200px-Flag_of_Turkey.svg.png",
        "UNITED ARAB EMIRATES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/1920px-Flag_of_the_United_Arab_Emirates.svg.png",
        "UNITED KINGDOM" to "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Flag_of_the_United_Kingdom_%281-2%29.svg/1200px-Flag_of_the_United_Kingdom_%281-2%29.svg.png",
        "UNITED STATES" to "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/1920px-Flag_of_the_United_States.svg.png",
        "UKRAINE" to "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/1200px-Flag_of_Ukraine.svg.png",
        "URUGUAY" to "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/1280px-Flag_of_Uruguay.svg.png",
        "UZBEKISTAN" to "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/1200px-Flag_of_Uzbekistan.svg.png",
    )

    val airlineDict = mapOf<String, String>(
        "AMERICAN AIRLINES" to "https://upload.wikimedia.org/wikipedia/en/thumb/2/23/American_Airlines_logo_2013.svg/1200px-American_Airlines_logo_2013.svg.png?20210814001348",
        "EL AL ISRAEL AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Logo_of_El_Al_Israel_Airlines.svg/1200px-Logo_of_El_Al_Israel_Airlines.svg.png",
        "RYANAIR" to "https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Ryanair.svg/1200px-Ryanair.svg.png?20210818173449",
        "WIZZAIR" to "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Wizz_Air_logo_2015.svg/195px-Wizz_Air_logo_2015.svg.png",
        "AIR PORTUGAL" to "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/TAP-Portugal-Logo.svg/441px-TAP-Portugal-Logo.svg.png",
        "UPS AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/United_Parcel_Service_logo_2014.svg/800px-United_Parcel_Service_logo_2014.svg.png",
        "WIZZ AIR ABU DHABI" to "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Wizz_Air_logo_2015.svg/195px-Wizz_Air_logo_2015.svg.png",
        "ARKIA  ISRAELI  AIRLINES" to "https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/Arkia_logo.svg/392px-Arkia_logo.svg.png?20181026095256",
        "AIR SEYCHELLES" to "https://upload.wikimedia.org/wikipedia/en/thumb/b/b1/Air_Seychelles_logo.svg/303px-Air_Seychelles_logo.svg.png?20150111214656",
        "PEGASUS AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pegasus_Airlines_logo.svg/353px-Pegasus_Airlines_logo.svg.png",
        "QANTAS AIRWAYS" to "https://upload.wikimedia.org/wikipedia/en/thumb/0/02/Qantas_Airways_logo_2016.svg/188px-Qantas_Airways_logo_2016.svg.png?20161027143102",
        "THAI AIRWAYS" to "https://upload.wikimedia.org/wikipedia/en/thumb/5/58/Thai_Airways_Logo.svg/768px-Thai_Airways_Logo.svg.png?20210131141507",
        "VIETNAM AIRLINES" to "https://upload.wikimedia.org/wikipedia/en/thumb/b/b6/Vietnam_Airlines_logo_2015.svg/453px-Vietnam_Airlines_logo_2015.svg.png?20230121032939",
        "IBERIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Logotipo_de_Iberia.svg/600px-Logotipo_de_Iberia.svg.png",
        "VUELING AIRLINES S.A." to "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Logo_Vueling.svg/1152px-Logo_Vueling.svg.png",
        "CHALLENGE AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/d/d8/CHALLENGE_AIRLINES_BE.png",
        "WIZZ UK" to "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Wizz_Air_logo_2015.svg/195px-Wizz_Air_logo_2015.svg.png",
        "TAROM - RUMANIAN AIR TRANSPORT" to "https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/TAROM_Logo_%28blue%29.svg/495px-TAROM_Logo_%28blue%29.svg.png?20230121153758",
        "ROYAL  JORDANIAN" to "https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Royal_Jordanian_Logo.svg/420px-Royal_Jordanian_Logo.svg.png?20100701152515",
        "AIR SERBIA" to "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Air_Serbia_logo-en.svg/300px-Air_Serbia_logo-en.svg.png?20181026103635",
        "TURKISH AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Turkish_Airlines_logo_2019_compact.svg/317px-Turkish_Airlines_logo_2019_compact.svg.png",
        "AIR INDIA" to "https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/Air_India_Logo.svg/507px-Air_India_Logo.svg.png?20221015023039",
        "EMIRATES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Emirates_logo.svg/849px-Emirates_logo.svg.png",
        "FLYDUBAI" to "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Fly_Dubai_logo_2010_03.svg/237px-Fly_Dubai_logo_2010_03.svg.png",
        "ISRAIR AIRLINES" to "https://upload.wikimedia.org/wikipedia/en/0/01/Israir-logo2.jpg?20050325202648",
        "LUFTHANSA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Lufthansa_Logo_2018.svg/768px-Lufthansa_Logo_2018.svg.png",
        "ALL NIPPON AIRWAYS" to "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/All_Nippon_Airways_Logo.svg/450px-All_Nippon_Airways_Logo.svg.png",
        "BRUSSELS AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Brussels_airlines_logo_2021.svg/140px-Brussels_airlines_logo_2021.svg.png",
        "UNITED AIRLINES" to "https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/United_Airlines_Logo.svg/729px-United_Airlines_Logo.svg.png?20210309002057",
        "AUSTRIAN AIRLINES" to "https://upload.wikimedia.org/wikipedia/en/thumb/8/81/Austrian_Airlines_logo.svg/1920px-Austrian_Airlines_logo.svg.png",
        "DELTA AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Delta_logo.svg/768px-Delta_logo.svg.png",
        "AEGEAN  AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Aegean_Airlines_Logo_2020.svg/338px-Aegean_Airlines_Logo_2020.svg.png",
        "AERO MEXICO" to "https://upload.wikimedia.org/wikipedia/en/thumb/d/d4/Aerom%C3%A9xico_logo.svg/768px-Aerom%C3%A9xico_logo.svg.png?20201116234841",
        "AEROLINEAS ARGENTINAS S.A." to "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Aerol%C3%ADneas_Argentinas_Logo_2010.svg/768px-Aerol%C3%ADneas_Argentinas_Logo_2010.svg.png",
        "ETHIOPIAN AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Ethiopian_Airlines_Logo.svg/855px-Ethiopian_Airlines_Logo.svg.png",
        "AIR FRANCE" to "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Air_France_Logo.svg/1920px-Air_France_Logo.svg.png",
        "K.L.M." to "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/KLM_logo.svg/525px-KLM_logo.svg.png",
        "SWISS INT`L  AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Swiss_International_Air_Lines_Logo_2011.svg/300px-Swiss_International_Air_Lines_Logo_2011.svg.png",
        "LOT POLISH AIRLINES" to "https://upload.wikimedia.org/wikipedia/en/thumb/3/3d/LOT_Polish_Airlines.svg/300px-LOT_Polish_Airlines.svg.png?20171126210848",
        "SILK WAY WEST AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Silk_Way_West_Airlines_logo.svg/1920px-Silk_Way_West_Airlines_logo.svg.png",
        "BRITISH AIRWAYS PLC" to "https://upload.wikimedia.org/wikipedia/tr/thumb/4/42/British_Airways_Logo.svg/363px-British_Airways_Logo.svg.png?20200809095614",
        "VIRGIN ATLANTIC AIRWAYS" to "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Virgin_Atlantic_logo_2018.svg/1920px-Virgin_Atlantic_logo_2018.svg.png",
        "ROYAL AIR MAROC" to "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Logo_Royal_Air_Maroc.svg/768px-Logo_Royal_Air_Maroc.svg.png",
        "GULF AIR - BAHREIN" to "https://upload.wikimedia.org/wikipedia/en/thumb/9/90/Gulf_Air_Logo_2018.svg/768px-Gulf_Air_Logo_2018.svg.png?20210722112139",
        "FEDERAL EXPRESS" to "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/FedEx_Corporation_-_2016_Logo.svg/1920px-FedEx_Corporation_-_2016_Logo.svg.png",
        "ATLAS AIR Inc." to "https://upload.wikimedia.org/wikipedia/en/e/e4/Atlas_Air_logo.png?20220603171738",
        "AIR CANADA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Air_Canada_Logo.svg/768px-Air_Canada_Logo.svg.png",
        "ג.א.ד טיסות בעמ" to "https://gadflights.com/wp-content/uploads/2022/06/GAD-ICON-Transperant-background-white-1024x363.png",
        "JETBLUE AIRWAYS CORPORATION" to "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/JetBlue_Airways_Logo.svg/878px-JetBlue_Airways_Logo.svg.png",
        "TUS AIRWAYS" to "https://upload.wikimedia.org/wikipedia/commons/9/92/Tus_Airways_Logo.png",
        "חץ תעופה" to "https://arrowaviation.biz/wp-content/uploads/2022/02/WEB-SITE.png",
        "SIBERIA AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/S7_new_logo.svg/300px-S7_new_logo.svg.png",
        "BLUE BIRD AIRWAYS" to "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Bluebird_Airways_Logo.png/375px-Bluebird_Airways_Logo.png",
        "NEOS" to "https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/Neos_logo.svg/263px-Neos_logo.svg.png",
        "AZIMUTH AIRLINES" to "https://www.telaviv-airport.com/images/airlines17/azimuth-airlines.png",
        "RED WINGS AIRLINES" to "https://upload.wikimedia.org/wikipedia/en/0/0e/Red_Wings_Logo_Transparent.png",
        "EASY JET SWITZERLAND" to "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/EasyJet_logo.svg/768px-EasyJet_logo.svg.png",
        "ETIHAD AIRWAYS" to "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Etihad-airways-logo.svg/375px-Etihad-airways-logo.svg.png",
        "EASYJET EUROPE AIRLINE" to "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/EasyJet_logo.svg/768px-EasyJet_logo.svg.png",
        "ENTER AIR- E4" to "https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Enter_Air_logo.png/300px-Enter_Air_logo.png",
        "TRANSAVIA FRANCE" to "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Transavia_logo.svg/1920px-Transavia_logo.svg.png",
        "MNG CARGO AIRLINES" to "https://adminsite.tigeraviation.aero/Images/News/id11.png",
        "EASYJET" to "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/EasyJet_logo.svg/768px-EasyJet_logo.svg.png",
        "AIR EUROPA Lineas Aereas S.A.U" to "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Air_Europa_Logo_%282015%29.svg/501px-Air_Europa_Logo_%282015%29.svg.png",
        "ITALIA TRASPORTO AEREO" to "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/ITA_Airways_Logo.svg/1920px-ITA_Airways_Logo.svg.png",
        "EGYPTAIR AIRLINES" to "https://upload.wikimedia.org/wikipedia/en/thumb/c/ca/Egypt_Air.svg/1200px-Egypt_Air.svg.png",
        "GEORGIAN AIRWAYS" to "https://upload.wikimedia.org/wikipedia/en/thumb/4/40/Georgian_Airways_logo.svg/1920px-Georgian_Airways_logo.svg.png",
        "SAN MARINO AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Logo_of_El_Al_Israel_Airlines.svg/1920px-Logo_of_El_Al_Israel_Airlines.svg.png",
        "C.A.L ISRAELI CARGO" to "https://www.viola-group.com/wp-content/uploads/2017/11/cal-cargo-airlines-logo-300x145.png",
        "KOREAN AIR" to "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/KoreanAir_logo.svg/1920px-KoreanAir_logo.svg.png",
        "NETJETS" to "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/NetJets_logo.svg/1920px-NetJets_logo.svg.png",
        "AIR MOLDOVA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Air_Moldova.svg/1920px-Air_Moldova.svg.png",
        "FINNAIR" to "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Finnair_Logo.svg/1920px-Finnair_Logo.svg.png",
        "CZECH AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Czech_Airlines_Logo.svg/768px-Czech_Airlines_Logo.svg.png",
        "SMARTWINGS" to "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Smartwings_logo.svg/1920px-Smartwings_logo.svg.png",
        "CATHAY PACIFIC AIRWAYS" to "https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Cathay_Pacific_logo.svg/645px-Cathay_Pacific_logo.svg.png",
        "UZBEKISTAN AIR" to "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Uzbekistan_Airways_logo.svg/1920px-Uzbekistan_Airways_logo.svg.png",
        "SUN EXPRESS" to "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/SunExpress_Logo.svg/1920px-SunExpress_Logo.svg.png",
        "HISKY EUROPE SRL" to "https://upload.wikimedia.org/wikipedia/en/f/f8/HiSky_logo.png",
        "AZERBAIJAN AIRLINES" to "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/Azerbaijan_Airlines_logo.svg/1280px-Azerbaijan_Airlines_logo.svg.png",
        "TAILWIND AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Tailwind_Airlines_Logo.svg/1920px-Tailwind_Airlines_Logo.svg.png",
        "CORONDON AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Corendon_Airlines_Logo_2017.svg/1920px-Corendon_Airlines_Logo_2017.svg.png",
        "CYPRUS AIRWAYS" to "https://upload.wikimedia.org/wikipedia/en/thumb/6/6a/Cyprus_Airways_%282017%29_logo.svg/1920px-Cyprus_Airways_%282017%29_logo.svg.png",
        "HAINAN AIRLINES" to "https://upload.wikimedia.org/wikipedia/en/thumb/c/cd/Hainan_Airlines_Logo.svg/1920px-Hainan_Airlines_Logo.svg.png",
        "BULGARIA  AIR" to "https://upload.wikimedia.org/wikipedia/en/thumb/3/35/Bulgaria_Air_logo-en.svg/1920px-Bulgaria_Air_logo-en.svg.png",
        "NORWEGIAN AIR SHUTTLE" to "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Norwegian_Logo.svg/375px-Norwegian_Logo.svg.png",
        "TRANSAVIA" to "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Transavia_logo.svg/1920px-Transavia_logo.svg.png",
        "HISKY" to "https://upload.wikimedia.org/wikipedia/en/f/f8/HiSky_logo.png",
        "AIR BALTIC" to "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/AirBaltic_logo_green_bkgd.svg/1920px-AirBaltic_logo_green_bkgd.svg.png",
        "FLYONE ARMENIA LLC" to "https://upload.wikimedia.org/wikipedia/commons/c/c3/FLYONE_Armenia_logo_no_background.png",
        "BUZZ AIR" to "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Buzz_%28Ryanair%29_logo.svg/1920px-Buzz_%28Ryanair%29_logo.svg.png",
        "EUROPEAN AIR TRANSPORT" to "https://upload.wikimedia.org/wikipedia/de/thumb/8/8d/European_Air_Transport_Logo.svg/1200px-European_Air_Transport_Logo.svg.png",
        "LAUFER GHI" to "https://israeltravel.co.il/wp-content/uploads/laufer1.png",
        "CATHAY PACIFIC AIRWAYS" to "https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Cathay_Pacific_logo.svg/645px-Cathay_Pacific_logo.svg.png?20150731225417",
        "FINNAIR" to "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Finnair_Logo.svg/300px-Finnair_Logo.svg.png",
        "ONUR AIR" to "https://upload.wikimedia.org/wikipedia/en/thumb/0/0a/Onur_Air_logo.svg/1920px-Onur_Air_logo.svg.png",
        "RED WINGS" to "https://upload.wikimedia.org/wikipedia/en/0/0e/Red_Wings_Logo_Transparent.png",
        "SKYUP AIRLINES" to "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/SkyUp_Airlines_logo.svg/1920px-SkyUp_Airlines_logo.svg.png",
        "UKRAINE INTL AIR" to "https://upload.wikimedia.org/wikipedia/he/thumb/e/ee/Ukraine_International_Airlines_Logo.svg/570px-Ukraine_International_Airlines_Logo.svg.png?20131017162112",
        "BEES AIRLINE" to "https://upload.wikimedia.org/wikipedia/commons/5/57/Bees_Airlines_Logo.png",
        "QUALITY AIR SERVICES" to "https://www.qasisrael.co.il/wp-content/uploads/2019/04/logo.png",
        "Jordan Aviation" to "https://upload.wikimedia.org/wikipedia/he/4/40/Logo_jordan_aviation.jpg",
        "USA AIR FORCE" to "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/US_Air_Force_Logo_Solid_Colour.svg/1154px-US_Air_Force_Logo_Solid_Colour.svg.png",
        "AIR HAMBURG" to "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Air_Hamburg_Logo.svg/900px-Air_Hamburg_Logo.svg.png",
        "BLUE AIR AVIATION" to "https://www.flyblueair.com/Themes/BlueAir.Theme/content/logo-mob.png",
        "FLYONE" to "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Flyone-logo-1.1.svg/1920px-Flyone-logo-1.1.svg.png",
        "POSTE AIR CARGO" to "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Poste_Air_Cargo_logo.svg/825px-Poste_Air_Cargo_logo.svg.png",
        "AERO HANDLING" to "https://www.aerohandling.com/media/main/logo-1.png",
        "vista jet air" to "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/VistaJet_logo.svg/624px-VistaJet_logo.svg.png",
        "שינו תעופה" to "https://shinoaviation.com/themes/sa/logo.png",
        "TBILISI AIRWAYS LLC" to "https://scontent.ftlv20-1.fna.fbcdn.net/v/t39.30808-6/221920138_106223791750695_5173722929858533106_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=33WEzoKTmSYAX9od2mh&_nc_ht=scontent.ftlv20-1.fna&oh=00_AfAuPoL-EgZcu6cFBpl7Ka8MzrFfzRpuqmMjkNwKcX8eaA&oe=63ED5E2E",
        "תעשיה אווירית- נסויי טיסה" to "https://upload.wikimedia.org/wikipedia/he/thumb/c/cf/Israel_Air_Industry.svg/300px-Israel_Air_Industry.svg.png",
        "א.י.מ. תעופה בעמ" to "https://www.atec-amt.org/uploads/1/0/7/5/10756256/aim-2022-logo-rgb_orig.png",
        "לייף אייר" to "https://www.iaa.gov.il/media/itvefq5g/lifeair.jpg",
        "רעות נתיבי אוויר" to "https://www.powervamp.com/wp-content/uploads/2018/07/reut-airways-gpu-1.png"
    )
}